name: Release Packages
description: Releases the goorm-cli and goorm packages

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - uses: goreleaser/goreleaser-action@v6
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 